In [1]:
import pandas as pd
import numpy as np

In [3]:
image_ids = pd.read_csv("node__field_image_identifier.csv")

In [4]:
image_ids.head()

,bundle,deleted,entity_id,revision_id,langcode,delta,field_image_identifier_value
0,documents,0,498,99682,en,0,3242561
1,documents,0,498,99682,en,1,3242562
2,documents,0,498,99682,en,2,3242563
3,documents,0,498,99682,en,3,3242564
4,documents,0,498,99682,en,4,3242565

In [6]:
lengths = [10, 107, 118, 12, 13]

# Extract the filenames
filenames = image_ids['field_image_identifier_value'].astype(str).tolist()

# Split into chunks and join with '|'
chunks = []
start = 0
for length in lengths:
    end = start + length
    chunk = filenames[start:end]
    chunks.append('|'.join(chunk))
    start = end

# Create a new DataFrame
new_df = pd.DataFrame({
    "chunk_id": range(1, len(chunks) + 1),
    "filenames_combined": chunks
})

print(new_df)

   chunk_id                                 filenames_combined
0         1  3242561|3242562|3242563|3242564|3242565|324256...
1         2  3242571|3242572|3242573|3242574|3242575|324257...
2         3  3242678|3242679|3242680|3242681|3242682|324268...
3         4  3242796|3242797|3242798|3242799|3242800|324280...
4         5  3242808|3242809|3242810|3242811|3242812|324281...

In [7]:
new_df['ID'] = [9653, 9654, 9655, 498, 9656]
new_df

   chunk_id                                 filenames_combined    ID
0         1  3242561|3242562|3242563|3242564|3242565|324256...  9653
1         2  3242571|3242572|3242573|3242574|3242575|324257...  9654
2         3  3242678|3242679|3242680|3242681|3242682|324268...  9655
3         4  3242796|3242797|3242798|3242799|3242800|324280...   498
4         5  3242808|3242809|3242810|3242811|3242812|324281...  9656

In [9]:
new_df.to_csv('498_fix.csv', index = False)