In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
doc_catalog = pd.read_csv('document_catalog_20250815.csv')

In [38]:
doc_catalog['Dateline'][2536]

'February 8, 1967\nMr. Richard A. Russell45 Kirkwood RoadWest Hartford, Connecticut 06117'

In [3]:
doc_catalog.columns

Index(['ID', 'Box', 'title', 'Document Date', 'Document Length',
       'Manuscript Type', 'Collection', 'Source', 'Internal Notes',
       'Workflow Stage', 'Object Type', 'Author', 'Keywords', 'Head',
       'Document Top', 'Dateline', 'Salutation', 'Document Body', 'Signature',
       'Post Script', 'Document Extra', 'Marginalia', 'Enclosure', 'Footnote',
       'General', 'Image Identifier', 'Response'],
      dtype='object')

In [4]:
doc_catalog['Object Type'].value_counts()

Object Type
Letter       8013
Speech        441
Article       112
Ephemera       46
Report         18
Pamphlet        8
Essay           4
Interview       4
Legal           4
Name: count, dtype: int64

In [5]:
letters = doc_catalog[doc_catalog['Object Type'] == 'Letter']

In [7]:
letters['Workflow Stage'].value_counts()

Workflow Stage
Cataloged       6744
Transcribed      880
Proof read       368
Early Access      19
Digitized          2
Name: count, dtype: int64

In [8]:
letters_proofed = letters[(letters['Workflow Stage'] == 'Proof read') | (letters['Workflow Stage'] == 'Early Access')]

In [9]:
letters_proofed

,ID,Box,title,Document Date,Document Length,Manuscript Type,Collection,Source,Internal Notes,Workflow Stage,...,Document Body,Signature,Post Script,Document Extra,Marginalia,Enclosure,Footnote,General,Image Identifier,Response
1907,107,Box 1 Folder 21,"Layhmond Robinson to Julian Bond, September 23...","Tue, 09/23/1969 - 12:00",1.0,"Typed, Signed, Autograph, Letterhead",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",This document is a letter from Layhmond Robins...,Early Access,...,You were - - as expected - - the hit of the In...,"Sincerely,\n[Signature]\nLayhmond Robinson\nPu...",NaN,Mr. Julian Bond\nRepresentative\nState House\n...,NaN,Speech at Conference of Black Elected Official...,NaN,NaN,3202346,NaN
1963,155,Box 4 Folder 24,"Letter from Nancy E. Travis to Julian Bond, Fe...","Mon, 02/24/1975 - 12:00",2.0,"Typed, Copy",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",There are four items in this folder. This entr...,Early Access,...,I was delighted to hear that you were going to...,"Sincerely,\n[Signature]\nNancy E. Travis, Dire...",NaN,NaN,NaN,NaN,NaN,NaN,"2857956, 2857957",NaN
2000,211,Box 5 Folder 28,"To Julian Bond from Jean Carey Bond, May 12, 1976","Wed, 05/12/1976 - 12:00",3.0,"Typed, Signed, Autograph, Letterhead, Copy",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Scanning notes: There are three documents in B...,Early Access,...,[Bond wrote two days of his 1976 political dia...,NaN,NaN,NaN,NaN,NaN,NaN,Political Diary kept by Julian Bond concerning...,"2858870, 2858869, 2858868",NaN
2005,206,Box 5 Folder 25,"Letter to Prospective Audiences, and Envelope","Wed, 01/01/1975 - 12:00\n - Fri, 12/31/1976 - ...",2.0,"Handwritten, Typed, Letterhead",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",5/20/2022 - Reviewed by KZantow\nScanning note...,Early Access,...,[Handwritten note on Georgia State Senate lett...,Julian Bond\n,"p.s. My office assistant, Ms. Noe, will be abl...",NaN,NaN,NaN,NaN,NaN,"2858727, 2858728",NaN
2057,273,Box 6 Folder 18,"From Julian Bond to Michael St. John, 7 June 1...","Tue, 06/07/1977 - 12:00",5.0,"Typed, Version",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",There are two items in this folder. This entry...,Early Access,...,"June 7, 1977\nDear Mr. St. John:\nHere is the ...","\nSincerely,\n \nJulian Bond",NaN,NaN,NaN,NaN,NaN,NaN,"3204041, 3204042, 3204043, 3204044, 3204045",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,4189,Box 15 Folder 1,"From Julian Bond to Menthalia Bolton, 9 Jun 1970","Tue, 06/09/1970 - 12:00",1.0,"Copy, Typed",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Bulk imported. The letters to the kids who are...,Early Access,...,Thank you for your letter. I certainly do reme...,"Sincerely,\nJulian Bond",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5711,4682,Box 15 Folder 2,"From Julian Bond to Josephine Chally, 22 Sep 1970","Tue, 09/22/1970 - 12:00",1.0,"Copy, Signed, Typed",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Bulk imported. Original letter not in collecti...,Early Access,...,"I am afraid you have misunderstood my remarks,...","Sincerely,\n[Faint copy of signature]\nJulian ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5712,4780,Box 15 Folder 3,"From Julian Bond to Jeannie Mooney, 21 Oct 1970","Wed, 10/21/1970 - 12:00",1.0,"Copy, Signed, Typed",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Bulk imported.\nEditorial Notes:\n\nPublishing...,Early Access,...,I heard about the incident of the shoes and bl...,"Sincerely,\n[Copy of signature]\nJulian Bond",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713,4910,Box 15 Folder 3,"From Julian Bond to Dustin Hoffman, 24 Nov 1970","Tue, 11/24/1970 - 12:00",1.0,"Copy, Signed, Typed",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Bulk imported.\nEditorial Notes:\n\nConcerns S...,Early Access,...,Your accountant has forwarded to my office you...,"Sincerely,\n[Copy of signature]\nJulian Bond",NaN,cc: Southern Elections Fund,NaN,NaN,NaN,NaN,NaN,NaN
5715,5811,Box 15 Folder 7,"From Julian Bond to Coretta Scott King, 3 Aug ...","Tue, 08/03/1971 - 12:00",2.0,"Copy, Typed",Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Bulk imported.\nEditorial Notes:\n\nIncludes d...,Early Access,...,"Under separate cover, I am sending you a copy ...","Sincerely,\nJulian Bond",NaN,enclosures,NaN,Confidential Memorandum on 1971-72 Political S...,NaN,NaN,NaN,NaN

In [14]:
letters_proofed['Document Top'].notna().value_counts()

Document Top
False    377
True      10
Name: count, dtype: int64

In [17]:
export = letters_proofed[letters_proofed['Dateline'].notna()][['ID', 'title', 'Document Date', 'Dateline']]

In [19]:
export.to_csv('OpenRefine_export.csv')

In [20]:
import spacy

# Load a pre-trained English language model
nlp = spacy.load("en_core_web_sm")

text = "The package should be delivered to 123 Main Street, Anytown, CA 90210."

# Process the text with the NLP model
doc = nlp(text)

# Iterate over named entities in the document
for ent in doc.ents:
    # Check if the entity label is a geopolitical entity (GPE) or location
    if ent.label_ == "GPE" or ent.label_ == "LOC":
        print(f"Potential address component: {ent.text} ({ent.label_})")

Potential address component: Anytown (GPE)

In [22]:
! pip install usaddress

Collecting usaddress
  Downloading usaddress-0.5.16-py3-none-any.whl.metadata (6.7 kB)
Collecting python-crfsuite>=0.7 (from usaddress)
  Downloading python_crfsuite-0.9.11-cp312-cp312-win_amd64.whl.metadata (4.4 kB)
Collecting probableparsing (from usaddress)
  Downloading probableparsing-0.0.1-py2.py3-none-any.whl.metadata (908 bytes)
Downloading usaddress-0.5.16-py3-none-any.whl (70 kB)
Downloading python_crfsuite-0.9.11-cp312-cp312-win_amd64.whl (301 kB)
Downloading probableparsing-0.0.1-py2.py3-none-any.whl (3.1 kB)
Installing collected packages: probableparsing, python-crfsuite, usaddress

   ---------------------------------------- 3/3 [usaddress]

Successfully installed probableparsing-0.0.1 python-crfsuite-0.9.11 usaddress-0.5.16

In [25]:
import pandas as pd
import usaddress

data = {'full_address': ['123 Main St, Anytown, CA 90210', 
                         '456 Oak Ave, Otherville, NY 10001']}
df = pd.DataFrame(data)

def parse_address_components(address):
    try:
        parsed_address = usaddress.tag(address)[0]
        return parsed_address
    except usaddress.RepeatedLabelError:
        pass

df_parsed = df['full_address'].apply(parse_address_components).apply(pd.Series)
df = pd.concat([df, df_parsed], axis=1)

print(df)

                        full_address AddressNumber StreetName  \
0     123 Main St, Anytown, CA 90210           123       Main
1  456 Oak Ave, Otherville, NY 10001           456        Oak

  StreetNamePostType   PlaceName StateName ZipCode
0                 St     Anytown        CA   90210
1                Ave  Otherville        NY   10001

In [26]:
df_parsed = export['Dateline'].apply(parse_address_components).apply(pd.Series)
df_parsed

,OccupancyType,OccupancyIdentifier,SubaddressType,SubaddressIdentifier,AddressNumber,StreetName,StreetNamePostType,PlaceName,StateName,Recipient,ZipCode,StreetNamePostDirectional,USPSBoxGroupType,USPSBoxGroupID,USPSBoxType,USPSBoxID,StreetNamePreDirectional,BuildingName,AddressNumberSuffix
1907,September,"23, 1969",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963,February,"24, 1975",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,October,"17, 1988",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2391,June,"2, 1972",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2393,May,"14, 1971",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5711,NaN,NaN,NaN,NaN,402,Jefferson\n,NaN,Morris,Illinois,"September 22, 1970\n Ms. Josephine Chally\n",60450,NaN,NaN,NaN,NaN,NaN,East,NaN,1/2
5712,NaN,NaN,NaN,NaN,1141,Russell,Drive\n,Decatur,Georgia,"October 21, 1970\n Miss Jeannie Mooney\n",30033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5715,NaN,NaN,August,3,1971\n,Mrs. Coretta Scott King\n 234 Sunset,Avenue,Atlanta,Georgia,NaN,30314,NW\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
export.head(50)

,ID,title,Document Date,Dateline
1907,107,"Layhmond Robinson to Julian Bond, September 23...","Tue, 09/23/1969 - 12:00","September 23, 1969"
1963,155,"Letter from Nancy E. Travis to Julian Bond, Fe...","Mon, 02/24/1975 - 12:00","February 24, 1975"
2166,366,"Memo concerning Voting Rights Act Amendments, ...","Mon, 10/17/1988 - 12:00","October 17, 1988"
2391,643,Speech File Material: National Urban League Ve...,"Fri, 06/02/1972 - 12:00","June 2, 1972"
2393,641,Speech File Material: Memo from Georgia Depart...,"Fri, 05/14/1971 - 12:00","May 14, 1971"
2461,689,"To Julian Bond from Dorothy Eldridge, 9 Jan 1967","Mon, 01/09/1967 - 12:00","January 9, 1967\nThe Honorable Julian Bond\n30..."
2462,688,"From Julian Bond to Dorothy Eldridge, 3 Feb 1967","Fri, 02/03/1967 - 12:00","February 3, 1967\nMrs. Dorothy Eldridge\nNew J..."
2465,685,"To Julian Bond from Fred C. Stern, 25 Jan 1967","Wed, 01/25/1967 - 12:00","January 25, 1967\nMr. Julian Bond\n823 Drummon..."
2466,684,"From Lester Lewis to Richard Hatcher, 3 Feb 1967","Fri, 02/03/1967 - 12:00","February 3, 1967\nThe Hon. Richard Hatcher\nCo..."
2498,736,"To Julian Bond from Sarah Ann Washington, 3 Fe...","Fri, 02/03/1967 - 12:00","Route 4, Box 415Savannah, Georgia 31405Februar..."
2499,735,"From Julian Bond to Sarah Ann Washington, 8 Fe...","Wed, 02/08/1967 - 12:00","February 8, 1967\nMiss Sarah Ann Washington Ro..."
2502,732,"From Julian Bond to Glenna B. Johnson, 7 Feb 1967","Tue, 02/07/1967 - 12:00","February 7, 1967\nMrs. Glenna B. Johnson, Prog..."
2518,759,"To Julian Bond from Vincent Barnard, 3 Feb 1967","Fri, 02/03/1967 - 12:00","287 Northside Dr., S.W., Apt 478\nAtlanta, Geo..."
2519,758,"To Julian Bond from Valeria Stafford, ca. 3 Fe...","Fri, 02/03/1967 - 12:00","Edmund Asa Ware Elementary\n569 Hunter St., N...."
2520,757,"To Julian Bond from Marcia Brown, ca. 3 Feb 1967","Fri, 02/03/1967 - 12:00","Edmund Asa Ware Elementary\n569 Hunter St., N...."
2521,756,"To Julian Bond from Iris Williams, ca. 3 Feb 1967","Fri, 02/03/1967 - 12:00","Edmund Asa Ware Elementary\n569 Hunter St., N...."
2522,755,"From Julian Bond to Iris Williams, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967"
2523,754,"From Julian Bond to Marcia Brown, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967"
2524,753,"From Julian Bond to Valeria Stafford, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967"
2525,752,"From Julian Bond to Vincent Barnard, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967"
2526,751,"From Julian Bond to Sonya Moulder, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967"
2527,750,"To Julian Bond from Howard H. Callaway, 24 Jan...","Tue, 01/24/1967 - 12:00","January 24, 1967\nMr. Julian Bond\n823 Drummon..."
2530,747,"From Julian Bond to Paul Booth, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967\nMr. Paul Booth5300 S. Greenw..."
2532,745,"From Julian Bond to Bynum Shaw, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967\nMr. Bynum Shaw 1527 Overbroo..."
2533,744,"To Julian Bond from Thelma Washington, 1 Feb 1...","Wed, 02/01/1967 - 12:00","Tuskegee Institute\nTuskegee InstituteAlabama,..."
2534,743,"From Julian Bond to Thelma Washington, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967\nMrs. Thelma WashingtonChairm..."
2535,742,"To Julian Bond from Richard A. Russell, 30 Jan...","Mon, 01/30/1967 - 12:00","Richard A. Russell 45 Kirkwood Road, West Hart..."
2536,741,"From Julian Bond to Richard A. Russell, 8 Feb ...","Wed, 02/08/1967 - 12:00","February 8, 1967\nMr. Richard A. Russell45 Kir..."
2538,739,"From Julian Bond to Robert K. Thrower, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967 \nMr. Robert K. Thrower, Pres..."
2540,737,"From Julian Bond to Ida M. Curtis, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967\nMrs. Ida M. CurtisDirector o..."
2542,778,"From Julian Bond to Tommy Swearingen, 9 Feb 1967","Thu, 02/09/1967 - 12:00","February 9, 1967\nMr. Tommy Swearingen1614 Clo..."
2544,776,"From Julian Bond to Richard Jackson, 9 Feb 1967","Thu, 02/09/1967 - 12:00","February 9, 1967\nMr. Richard JacksonP. O. Box..."
2557,763,"From Julian Bond to Rufus E. Clement, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967\nDr. Rufus E. Clement, Presid..."
2558,762,"From Julian Bond to A. E. Manley, 8 Feb 1967","Wed, 02/08/1967 - 12:00","February 8, 1967\nDr. A. E. Manley, President\..."
2559,761,"From Julian Bond to Eugene Clayton Calhoun, 8 ...","Wed, 02/08/1967 - 12:00","February 8, 1967\nDr. Eugene Clayton Calhoun\n..."
2560,760,"To Julian Bond from Sonya Moulder, ca. 3 Feb 1967","Fri, 02/03/1967 - 12:00","Edmund Asa Ware Elementary\n569 Hunter St., N...."
2561,801,"From Julian Bond to Charles Morgan (draft), ca...","Wed, 02/15/1967 - 12:00","Charles Morgan ACLU 5 Forsyth Street Atlanta, ..."
2562,800,"From Julian Bond to Charles Morgan, 15 Feb 1967","Wed, 02/15/1967 - 12:00","February 15, 1967\nMr. Charles Morgan ACLU 5 F..."
2580,782,"From Julian Bond to Mr. and Mrs. Ezell Blair, ...","Thu, 02/09/1967 - 12:00","February 9, 1967\nMr. and Mrs. Ezell Blair512 ..."
2581,781,"To Julian Bond from Beverly Ouisley, 5 Feb 196...","Sun, 02/05/1967 - 12:00","2980 Del Mar Lane S. W.Atlanta, GA. 30311Febru..."
2582,780,"From Julian Bond to Beverly Ouisley, 9 Feb 1967","Thu, 02/09/1967 - 12:00","February 9, 1967\nMiss Beverly Ouisley2980 Del..."
2585,820,"To Julian Bond from Mrs. Louise Andrews Sims, ...","Thu, 12/15/1966 - 12:00",American Friends Service CommitteeIncorporated...
2600,805,"From Julian Bond to Malcolm Willison, 15 Feb 1967","Wed, 02/15/1967 - 12:00","February 15, 1967\nMr. Malcolm WillisonSpeaker..."
2603,802,"From Julian Bond to Joseph T. Fuhrmann, 15 Feb...","Wed, 02/15/1967 - 12:00","February 15, 1967\nMr. Joseph T. Fuhrmann413 S..."
2615,832,"From Julian Bond to Arlo Tatum, 16 Feb 1967","Thu, 02/16/1967 - 12:00","February 16, 1967\nMr. Arlo Tatum Central Comm..."
2616,831,To Julian Bond from Mrs. Joseph D'Oronzio (Wen...,"Mon, 02/06/1967 - 12:00","1101 Livermore StreetYellow Springs, OhioFebru..."
2618,829,From Julian Bond to Mrs. Joseph D'Oronzio (Wen...,"Thu, 02/16/1967 - 12:00","February 16, 1967\nMrs. Joseph D'OronzioWomen ..."
2621,826,"To Julian Bond from Edward H. Beardsley, 10 Fe...","Fri, 02/10/1967 - 12:00",[Official Seal]\nUNIVERSITY OF SOUTH CAROLINA ...
2623,824,"From Julian Bond to Edward H. Beardsley, 16 Fe...","Thu, 02/16/1967 - 12:00","February 16, 1967\nMr. Edward H. BeardsleyAssi..."
2624,823,"To Julian Bond from Robert W. Lutnes, 2 Feb 1967","Thu, 02/02/1967 - 12:00",[letterhead]:Meredith PressDivision of Meredit...

In [52]:
def insert_newline(text: str) -> str:
    pattern = r'([a-z])([A-Z0-9])'
    return re.sub(pattern, r'\1\n\2', text)

In [57]:
datelines = []
for idx, row in export.iterrows():
    dateline = row['Dateline']
    dateline = dateline.replace('\xa0', '')
    dateline = insert_newline(dateline)
    dateline = dateline.split('\n')
    datelines.append(dateline)

In [58]:
datelines

[['September 23, 1969'],
 ['February 24,1975'],
 ['October 17, 1988'],
 ['June 2, 1972'],
 ['May 14, 1971'],
 ['January 9, 1967',
  'The Honorable Julian Bond',
  '306 Nelson Street',
  'Atlanta, Georgia'],
 ['February 3, 1967',
  'Mrs. Dorothy Eldridge',
  'New Jersey Committee for A Sane Nuclear Policy',
  '9 Park Street',
  'Montclair, New Jersey 07042'],
 ['January 25, 1967',
  'Mr. Julian Bond',
  '823 Drummond South West',
  'Atlanta, Georgia'],
 ['February 3, 1967',
  'The Hon. Richard Hatcher',
  'Councilman',
  'City Hall',
  'Gary, Indiana'],
 ['Route 4, Box 415Savannah, Georgia 31405February 3, 1967',
  'Julian Bond',
  'Georgia Representative',
  '823 Drummond Street'],
 ['February 8, 1967',
  'Miss Sarah Ann Washington',
  'Route 4, Box 415Savannah, Georgia'],
 ['February 7, 1967',
  'Mrs. Glenna B. Johnson, Program Chairman',
  'Des Moines Branch W.I.L.P.F.536 1/2 - 40th Street',
  'Des Moines, Iowa 50312'],
 ['287 Northside Dr., S.W., Apt 478',
  'Atlanta, Georgia 30313',
  'February 3, 1967'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['February 8, 1967'],
 ['February 8, 1967'],
 ['February 8, 1967'],
 ['February 8, 1967'],
 ['February 8, 1967'],
 ['January 24, 1967',
  'Mr. Julian Bond',
  '823 Drummond Street, S.W.',
  'Atlanta, Georgia 30314'],
 ['February 8, 1967',
  'Mr. Paul Booth',
  '5300 S. Greenwood',
  'Chicago, Illinois 60615'],
 ['February 8, 1967',
  'Mr. Bynum Shaw',
  '1527 Overbrook Avenue',
  'Winston-Salem, North Carolina 27104'],
 ['Tuskegee Institute',
  'Tuskegee Institute',
  'Alabama, 36088',
  'College of Arts and Sciences',
  'Division of Natural Sciences',
  'Department of Mathematics',
  'February 1, 1967',
  'Mr. Julian Bond',
  '823 Drummond Street',
  'Atlanta, Georgia 30314'],
 ['February 8, 1967',
  'Mrs. Thelma Washington',
  'Chairman of Interim Committee',
  'Tuskegee Institute',
  'Tuskegee, Alabama 36088'],
 ['Richard A. Russell',
  '45 Kirkwood Road, West Hartford, Connecticut 06117 Tel. 236-0849',
  'January 30, 1967',
  'Mr. Julian Bond',
  '823 Drummond Street, S.W.Atlanta, Georgia 30314'],
 ['February 8, 1967',
  'Mr. Richard A. Russell',
  '45 Kirkwood Road',
  'West Hartford, Connecticut 06117'],
 ['February 8, 1967',
  'Mr. Robert K. Thrower, President',
  'Robert K. Thrower, Inc."The Brick Man"1990 College Avenue, N. E.Atlanta, Georgia 30317'],
 ['February 8, 1967',
  'Mrs. Ida M. Curtis',
  'Director of Sales',
  'F C H Company, Inc.Suite 1111, Brunswick Building',
  '69 West Washington Street',
  'Chicago, Illinois 60602'],
 ['February 9, 1967',
  'Mr. Tommy Swearingen',
  '1614 Cloverdale Drive',
  'Savannah, Georgia 31402'],
 ['February 9, 1967',
  'Mr. Richard Jackson',
  'P. O. Box 321Union Springs, Alabama'],
 ['February 8, 1967',
  'Dr. Rufus E. Clement, President',
  'Atlanta University',
  'Atlanta, Georgia'],
 ['February 8, 1967',
  'Dr. A. E. Manley, President',
  'Spelman College',
  'Atlanta, Georgia'],
 ['February 8, 1967',
  'Dr. Eugene Clayton Calhoun',
  'Paine College',
  'Augusta, Georgia'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['Charles Morgan', 'ACLU5 Forsyth Street', 'Atlanta, Georgia'],
 ['February 15, 1967',
  'Mr. Charles Morgan',
  'ACLU5 Forsyth Street',
  'Atlanta, Georgia'],
 ['February 9, 1967',
  'Mr. and Mrs. Ezell Blair',
  '512 Purchase Street#2 ANew Bedford, Massachusetts'],
 ['2980 Del Mar Lane S. W.Atlanta, GA. 30311February 5, 1967',
  'Representative Julian Bond',
  'State Capitol',
  'Atlanta, GA.'],
 ['February 9, 1967',
  'Miss Beverly Ouisley',
  '2980 Del Mar Lane, S. W.Atlanta, Georgia 30311'],
 ['American Friends Service Committee',
  'Incorporated',
  '160 North Fifteenth Street, Philadelphia, Pennsylvania 19102Area Code 215 LOcust 3-9372',
  'Gilbert F. White',
  'Chairman',
  'Henry J. Cadbury',
  'Honorary Chairman',
  'Colin W. Bell',
  'Executive Secretary',
  'December 15, 1966',
  'Julian Bond',
  '823 Drummond S. W.Atlanta, Ga. 60614'],
 ['February 15, 1967',
  'Mr. Malcolm Willison',
  'Speakers Committee of the Capital District Friends of SNCC66 Union Avenue',
  'Schenectady, New York 12308'],
 ['February 15, 1967',
  'Mr. Joseph T. Fuhrmann',
  '413 South Highland Avenue',
  'Bloomington, Indiana'],
 ['February 16, 1967',
  'Mr. Arlo Tatum',
  'Central Committee for Conscientious Objectors',
  '2006 Walnut Street',
  'Philadelphia, Pennsylvania 19103'],
 ['1101 Livermore Street',
  'Yellow Springs, Ohio',
  'February 6, 1967',
  'Julian Bond',
  'National Council for New Politics',
  '250 West 57th Street',
  'New York, N.Y. 10019'],
 ['February 16, 1967',
  "Mrs. Joseph D'Oronzio",
  'Women for Peace',
  '1101 Livermore Street',
  'Yellow Springs, Ohio'],
 ['[Official Seal]',
  'UNIVERSITY OF SOUTH CAROLINACOLUMBIA, S. C. 29208',
  'Department of History',
  'Feb. 10, 1967',
  'Mr. Julien Bond, State Representative',
  'Georgia State Legislature',
  'Atlanta, Ga.'],
 ['February 16, 1967',
  'Mr. Edward H. Beardsley',
  'Assistant Professor of History',
  'University of South Carolina',
  'Columbia, South Carolina 29208'],
 ['[letterhead]:Meredith Press',
  'Division of Meredith Publishing Company',
  '250 Park Avenue, New York, New York 10017 · 986-8700',
  'February 2, 1967',
  'Mr. Julian Bond',
  'Georgia State Legislature',
  'Atlanta, Georgia'],
 ['February 16, 1967',
  'Mr. Helle Rätsep',
  'Kurekjla',
  'Tartu Rajoon',
  'Estonia',
  'U. S. S. R.'],
 ['May 15, 1967',
  'Mr. Langston Hughes',
  '20 East 127th Street',
  'New York, New York'],
 ['July 25, 1967',
  'Dr Martin Luther King, Jr.',
  'SCLC',
  'Auburn Avenue, NE',
  'Atlanta, Georgia'],
 ['3 September 1967',
  'Mr. Julian Bond',
  'Georgia State Legislature',
  'Atlanta, Georgia'],
 ['September 7, 1967',
  'Mr. Casper L. Jordan',
  'Editor',
  'Free Lance',
  '4610 Terrace Drive',
  'Niagara Falls, New York 14305'],
 ['[seal: STATE OF GEORGIA]',
  'House of Representatives',
  'Atlanta',
  'August 11, 1967'],
 ['September 1, 1967',
  'Mr. Julian Bond',
  '361 Lee Street S. W.Atlanta, Georgia'],
 ['September 7, 1967',
  'Mr. Andrew J. Young, Executive Director',
  'Southern Christian Leadership Conference',
  '334 Auburn Avenue, N. E.Atlanta, Georgia 30303'],
 ['August 17, 1967',
  'Hon. Rep. Julian Bond',
  'State Capitol Bldg.Atlanta, Georgia'],
 ['A[ug]ust 1, 1967',
  'Representative Julian Bond',
  'Georgia State Legislature',
  'Atlanta, Georgia'],
 ['September 7, 1967',
  'Mr. Donald Hynes',
  '80 Park Drive',
  'Eastchester, New York'],
 ['September 7, 1967',
  'Mr. Barry Hoffmanc/o Congressman R. Kastenmeier',
  '1203 House Office Building',
  'Washington, D.C.'],
 ['August 31, 1967',
  'Hon. Julian Bond',
  'House of Representatives',
  'Atlanta, Georgia'],
 ['House of Representatives', 'Atlanta', 'September 15, 1967'],
 ['Samuel G. Jackson, Jr.c/o Juanita Clarke',
  'Metropolitan Applied Research Center',
  '330 West 58th Street',
  'New York, New York'],
 ['September 8, 1967',
  'Mrs. Alberta Hall Nelson',
  'Letsche School',
  '1530 Cliff Street',
  'Pittsburgh, Pa. 15219'],
 ['September 8, 1967',
  'Mr. E. M. Laws',
  '137 Griffin Street, N. W.Atlanta, Georgia 30314'],
 ['September 8, 1967',
  "Mr. D'Army Bailey",
  'Law Student Civil Rights Research Council',
  '156 Fifth Avenue',
  'New York, New York'],
 ['September 18, 1967',
  'Mrs. Elizabeth Webb',
  '575 Peters Street#86Atlanta, Georgia'],
 ['P.O. Box 65Hampton, S. C.29924',
  'September 16, 1967',
  'Rep. Julain Bond',
  'House of Representatives',
  'Atlanta, Georgia'],
 ['September 8, 1967',
  'Representative Julian H. Bond',
  'Georgia House of Representatives',
  'Atlanta, Georgia'],
 ['September 15, 1967',
  "Mr. D'Army Bailey",
  'Law Students Civil Rights Research Council',
  '156 Fifth Avenue',
  'New York, New York'],
 ['September 15, 1967',
  'Mr. Elijah Hill, Jr.,President',
  'Progressive Club',
  '805 1/2 Wright Street',
  'Thomasville, Georgia'],
 ['September 13, 1967',
  'Representative Julian Bond',
  'House of Representatives',
  'Atlanta, Georgia'],
 ['September 28, 1967',
  'Mr. Barry Hoffman',
  'University of Wisconsin',
  'Young Democrats',
  'Madison, Wisconsin 53706'],
 ['September 28, 1967',
  'Mr. Elijah Hill, Jr.President',
  'Progressive Club',
  '805 1/2 Wright Street',
  'Thomasville, Georgia'],
 ['September 20, 1967',
  'Mr. Julian Bond',
  '361 Lee Street, S.W.Atlanta, Georgia'],
 ['March 4, 1968'],
 ['[Letterhead]',
  'Impact Symposium',
  'Vanderbilt University * Nashville, Tennessee',
  '[Typed.]',
  'March 26, 1968'],
 ['April 2, 1968'],
 ['Mrs. Martin Luther King Jr.',
  '234 Sunset Avenue N.W.',
  'Atlanta, Georgia 30314',
  'May 27, 1968'],
 ['May 3, 1968'],
 ['Mr. Robert S. Browne',
  'Black Economic Research Center',
  '112 West 120th St.New York, N. Y. 10027'],
 ['June 9, 1970',
  'Miss Menthalia Bolton',
  '94 Chestnut St., NW - #233',
  'Atlanta, Georgia 30314'],
 ['September 22, 1970',
  'Ms. Josephine Chally',
  '402 1/2 East Jefferson',
  'Morris, Illinois 60450'],
 ['October 21, 1970',
  'Miss Jeannie Mooney',
  '1141 Russell Drive',
  'Decatur, Georgia 30033'],
 ['November 24, 1970',
  'Mr. Dustin Hoffman',
  'c/o Hect, Brayer & Grill',
  '1501 Broadway',
  'New York, N.Y. 10036',
  'attn: Michael Hecht'],
 ['August 3, 1971',
  'Mrs. Coretta Scott King',
  '234 Sunset Avenue, NW',
  'Atlanta, Georgia 30314']]

In [61]:
date_pattern = re.compile(r'\b(?:\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|[A-Z][a-z]+ \d{1,2}, \d{4})\b')

def is_date(s: str) -> bool:
    return bool(date_pattern.search(s))

[[k for k in j if not is_date(k)] for j in datelines]

[[],
 ['February 24,1975'],
 [],
 [],
 [],
 ['The Honorable Julian Bond', '306 Nelson Street', 'Atlanta, Georgia'],
 ['Mrs. Dorothy Eldridge',
  'New Jersey Committee for A Sane Nuclear Policy',
  '9 Park Street',
  'Montclair, New Jersey 07042'],
 ['Mr. Julian Bond', '823 Drummond South West', 'Atlanta, Georgia'],
 ['The Hon. Richard Hatcher', 'Councilman', 'City Hall', 'Gary, Indiana'],
 ['Route 4, Box 415Savannah, Georgia 31405February 3, 1967',
  'Julian Bond',
  'Georgia Representative',
  '823 Drummond Street'],
 ['Miss Sarah Ann Washington', 'Route 4, Box 415Savannah, Georgia'],
 ['Mrs. Glenna B. Johnson, Program Chairman',
  'Des Moines Branch W.I.L.P.F.536 1/2 - 40th Street',
  'Des Moines, Iowa 50312'],
 ['287 Northside Dr., S.W., Apt 478', 'Atlanta, Georgia 30313'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 [],
 [],
 [],
 [],
 [],
 ['Mr. Julian Bond', '823 Drummond Street, S.W.', 'Atlanta, Georgia 30314'],
 ['Mr. Paul Booth', '5300 S. Greenwood', 'Chicago, Illinois 60615'],
 ['Mr. Bynum Shaw',
  '1527 Overbrook Avenue',
  'Winston-Salem, North Carolina 27104'],
 ['Tuskegee Institute',
  'Tuskegee Institute',
  'Alabama, 36088',
  'College of Arts and Sciences',
  'Division of Natural Sciences',
  'Department of Mathematics',
  'Mr. Julian Bond',
  '823 Drummond Street',
  'Atlanta, Georgia 30314'],
 ['Mrs. Thelma Washington',
  'Chairman of Interim Committee',
  'Tuskegee Institute',
  'Tuskegee, Alabama 36088'],
 ['Richard A. Russell',
  '45 Kirkwood Road, West Hartford, Connecticut 06117 Tel. 236-0849',
  'Mr. Julian Bond',
  '823 Drummond Street, S.W.Atlanta, Georgia 30314'],
 ['Mr. Richard A. Russell',
  '45 Kirkwood Road',
  'West Hartford, Connecticut 06117'],
 ['Mr. Robert K. Thrower, President',
  'Robert K. Thrower, Inc."The Brick Man"1990 College Avenue, N. E.Atlanta, Georgia 30317'],
 ['Mrs. Ida M. Curtis',
  'Director of Sales',
  'F C H Company, Inc.Suite 1111, Brunswick Building',
  '69 West Washington Street',
  'Chicago, Illinois 60602'],
 ['Mr. Tommy Swearingen', '1614 Cloverdale Drive', 'Savannah, Georgia 31402'],
 ['Mr. Richard Jackson', 'P. O. Box 321Union Springs, Alabama'],
 ['Dr. Rufus E. Clement, President', 'Atlanta University', 'Atlanta, Georgia'],
 ['Dr. A. E. Manley, President', 'Spelman College', 'Atlanta, Georgia'],
 ['Dr. Eugene Clayton Calhoun', 'Paine College', 'Augusta, Georgia'],
 ['Edmund Asa Ware Elementary',
  '569 Hunter St., N. W.',
  'Atlanta, Georgia 30314'],
 ['Charles Morgan', 'ACLU5 Forsyth Street', 'Atlanta, Georgia'],
 ['Mr. Charles Morgan', 'ACLU5 Forsyth Street', 'Atlanta, Georgia'],
 ['Mr. and Mrs. Ezell Blair',
  '512 Purchase Street#2 ANew Bedford, Massachusetts'],
 ['2980 Del Mar Lane S. W.Atlanta, GA. 30311February 5, 1967',
  'Representative Julian Bond',
  'State Capitol',
  'Atlanta, GA.'],
 ['Miss Beverly Ouisley', '2980 Del Mar Lane, S. W.Atlanta, Georgia 30311'],
 ['American Friends Service Committee',
  'Incorporated',
  '160 North Fifteenth Street, Philadelphia, Pennsylvania 19102Area Code 215 LOcust 3-9372',
  'Gilbert F. White',
  'Chairman',
  'Henry J. Cadbury',
  'Honorary Chairman',
  'Colin W. Bell',
  'Executive Secretary',
  'Julian Bond',
  '823 Drummond S. W.Atlanta, Ga. 60614'],
 ['Mr. Malcolm Willison',
  'Speakers Committee of the Capital District Friends of SNCC66 Union Avenue',
  'Schenectady, New York 12308'],
 ['Mr. Joseph T. Fuhrmann',
  '413 South Highland Avenue',
  'Bloomington, Indiana'],
 ['Mr. Arlo Tatum',
  'Central Committee for Conscientious Objectors',
  '2006 Walnut Street',
  'Philadelphia, Pennsylvania 19103'],
 ['1101 Livermore Street',
  'Yellow Springs, Ohio',
  'Julian Bond',
  'National Council for New Politics',
  '250 West 57th Street',
  'New York, N.Y. 10019'],
 ["Mrs. Joseph D'Oronzio",
  'Women for Peace',
  '1101 Livermore Street',
  'Yellow Springs, Ohio'],
 ['[Official Seal]',
  'UNIVERSITY OF SOUTH CAROLINACOLUMBIA, S. C. 29208',
  'Department of History',
  'Feb. 10, 1967',
  'Mr. Julien Bond, State Representative',
  'Georgia State Legislature',
  'Atlanta, Ga.'],
 ['Mr. Edward H. Beardsley',
  'Assistant Professor of History',
  'University of South Carolina',
  'Columbia, South Carolina 29208'],
 ['[letterhead]:Meredith Press',
  'Division of Meredith Publishing Company',
  '250 Park Avenue, New York, New York 10017 · 986-8700',
  'Mr. Julian Bond',
  'Georgia State Legislature',
  'Atlanta, Georgia'],
 ['Mr. Helle Rätsep', 'Kurekjla', 'Tartu Rajoon', 'Estonia', 'U. S. S. R.'],
 ['Mr. Langston Hughes', '20 East 127th Street', 'New York, New York'],
 ['Dr Martin Luther King, Jr.',
  'SCLC',
  'Auburn Avenue, NE',
  'Atlanta, Georgia'],
 ['3 September 1967',
  'Mr. Julian Bond',
  'Georgia State Legislature',
  'Atlanta, Georgia'],
 ['Mr. Casper L. Jordan',
  'Editor',
  'Free Lance',
  '4610 Terrace Drive',
  'Niagara Falls, New York 14305'],
 ['[seal: STATE OF GEORGIA]', 'House of Representatives', 'Atlanta'],
 ['Mr. Julian Bond', '361 Lee Street S. W.Atlanta, Georgia'],
 ['Mr. Andrew J. Young, Executive Director',
  'Southern Christian Leadership Conference',
  '334 Auburn Avenue, N. E.Atlanta, Georgia 30303'],
 ['Hon. Rep. Julian Bond', 'State Capitol Bldg.Atlanta, Georgia'],
 ['A[ug]ust 1, 1967',
  'Representative Julian Bond',
  'Georgia State Legislature',
  'Atlanta, Georgia'],
 ['Mr. Donald Hynes', '80 Park Drive', 'Eastchester, New York'],
 ['Mr. Barry Hoffmanc/o Congressman R. Kastenmeier',
  '1203 House Office Building',
  'Washington, D.C.'],
 ['Hon. Julian Bond', 'House of Representatives', 'Atlanta, Georgia'],
 ['House of Representatives', 'Atlanta'],
 ['Samuel G. Jackson, Jr.c/o Juanita Clarke',
  'Metropolitan Applied Research Center',
  '330 West 58th Street',
  'New York, New York'],
 ['Mrs. Alberta Hall Nelson',
  'Letsche School',
  '1530 Cliff Street',
  'Pittsburgh, Pa. 15219'],
 ['Mr. E. M. Laws', '137 Griffin Street, N. W.Atlanta, Georgia 30314'],
 ["Mr. D'Army Bailey",
  'Law Student Civil Rights Research Council',
  '156 Fifth Avenue',
  'New York, New York'],
 ['Mrs. Elizabeth Webb', '575 Peters Street#86Atlanta, Georgia'],
 ['P.O. Box 65Hampton, S. C.29924',
  'Rep. Julain Bond',
  'House of Representatives',
  'Atlanta, Georgia'],
 ['Representative Julian H. Bond',
  'Georgia House of Representatives',
  'Atlanta, Georgia'],
 ["Mr. D'Army Bailey",
  'Law Students Civil Rights Research Council',
  '156 Fifth Avenue',
  'New York, New York'],
 ['Mr. Elijah Hill, Jr.,President',
  'Progressive Club',
  '805 1/2 Wright Street',
  'Thomasville, Georgia'],
 ['Representative Julian Bond',
  'House of Representatives',
  'Atlanta, Georgia'],
 ['Mr. Barry Hoffman',
  'University of Wisconsin',
  'Young Democrats',
  'Madison, Wisconsin 53706'],
 ['Mr. Elijah Hill, Jr.President',
  'Progressive Club',
  '805 1/2 Wright Street',
  'Thomasville, Georgia'],
 ['Mr. Julian Bond', '361 Lee Street, S.W.Atlanta, Georgia'],
 [],
 ['[Letterhead]',
  'Impact Symposium',
  'Vanderbilt University * Nashville, Tennessee',
  '[Typed.]'],
 [],
 ['Mrs. Martin Luther King Jr.',
  '234 Sunset Avenue N.W.',
  'Atlanta, Georgia 30314'],
 [],
 ['Mr. Robert S. Browne',
  'Black Economic Research Center',
  '112 West 120th St.New York, N. Y. 10027'],
 ['Miss Menthalia Bolton',
  '94 Chestnut St., NW - #233',
  'Atlanta, Georgia 30314'],
 ['Ms. Josephine Chally', '402 1/2 East Jefferson', 'Morris, Illinois 60450'],
 ['Miss Jeannie Mooney', '1141 Russell Drive', 'Decatur, Georgia 30033'],
 ['Mr. Dustin Hoffman',
  'c/o Hect, Brayer & Grill',
  '1501 Broadway',
  'New York, N.Y. 10036',
  'attn: Michael Hecht'],
 ['Mrs. Coretta Scott King',
  '234 Sunset Avenue, NW',
  'Atlanta, Georgia 30314']]

In [56]:
datelines = [
    ["September 23, 1969"],
    ["Not a date"],
    ["February 24, 1975", "Some text"]
]

datelines = [
    [j for j in i if not is_date(j)]
    for i in datelines
]

print(datelines)

[[], ['Not a date'], ['Some text']]